### ISSUE TITLE
bug: I can't build the project through Gnome Builder

### ISSUE THREAD

**Issue by DivineBicycle** [GradienceTeam/Gradience#284] opened 2022-08-28 03:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I got this error:
 >/dev/null 2>&1
Error: module libsass: Child process exited with code 137

### To Reproduce

1. Clone the project and open it in Gnome Builder
2. Run the project through Gnome Builder

### Expected behavior

It should build

### Screenshots

 >/dev/null 2>&1
Error: module libsass: Child process exited with code 137

Error I get

### OS

Arch Linux

### Version

Latest Commit

### Installation method

Other

### Additional context

It works using flatpak-builder

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdwCustomizer** [comment] 2022-08-28 03:37
Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible. You can also join the matrix room.

**Comment by LyesSaadi** [comment] 2022-08-28 10:56
Hello, can you provide a more extensive error message?

**Comment by DivineBicycle** [comment] 2022-08-28 12:09
[Here's](https://gist.github.com/DivineBicycle/e076a5ef75028a0a18c6a127bd5b29b9) the build log

**Comment by tfuxu** [comment] 2022-08-28 15:14
@DivineBicycle Error 137 usually means that a process got killed by OOM (out-of-memory) killer. Are you maybe running this build on a virtual machine? If so, try to allocate more RAM to it.

**Comment by DivineBicycle** [comment] 2022-08-29 02:30
I'm not using a virtual machine, but I had systemd-oomd enabled so I will disable that service and try again.

**Comment by tfuxu** [comment] 2022-08-29 10:11
> I'm not using a virtual machine, but I had systemd-oomd enabled so I will disable that service and try again.

Ah yes, I had the same issue with systemd-oomd when I tried to reproduce your issue on vm, but in my case it also killed Builder.

**Comment by 0xMRTT** [comment] 2022-08-29 21:37
The app is coming in flathub repo. (Submission accepted and merged)

**Comment by daudix-UFO** [comment] 2022-08-30 00:37
Application available in GNOME Software

**Comment by daudix-UFO** [comment] 2022-08-30 00:39
Closing for now

**Comment by DivineBicycle** [comment] 2022-08-30 02:07
I tried again without OOMD enabled, and I got the same error. However I did not run out of memory. How odd. I'll upload the build log again. [Here](https://gist.github.com/DivineBicycle/e076a5ef75028a0a18c6a127bd5b29b9)

**Comment by daudix-UFO** [comment] 2022-08-30 02:23
OK, I reopen, anyway this is strange

**Comment by LyesSaadi** [comment] 2022-08-30 02:25
We also got a new piece of information : The stage at which the build fails is consistent, so no OOM business here.

**Comment by LyesSaadi** [comment] 2022-08-30 02:57
Can you maybe try to replace both `com.github.GradienceTeam.Gradience.json` and `com.github.GradienceTeam.Gradience.Devel.json` by this file : https://github.com/flathub/com.github.GradienceTeam.Gradience/blob/master/com.github.GradienceTeam.Gradience.json ?

At this point, I'm just so confused I'm asking you to try the more conventional method to build libsass. But, what's happening is that GCC is failing with error code 137. Unfortunately, libtool doesn't print the error, just the error code (why the fuck, btw), and, gcc does not document its error codes, sooooo, we're kinda working in the dark here.

**Comment by tfuxu** [comment] 2022-08-30 02:57
> I tried again without OOMD enabled, and I got the same error. However I did not run out of memory. How odd. I'll upload the build log again. [Here](https://gist.github.com/DivineBicycle/e076a5ef75028a0a18c6a127bd5b29b9)

That's really weird. I was able to compile every dependency on a 4GB ram vm, so maybe as Lyes says, there's no OOM business here. Maybe it is the version of Builder you're using (I'm on version 43.alpha1), that have that kinds of bugs. Here's my full build log [here](https://gist.github.com/tfuxu/d0b7838b47d9098e1743d9cd6d4c41fd) if you want to compare it with yours.

**Comment by tfuxu** [comment] 2022-08-30 03:03
> Can you maybe try to replace both `com.github.GradienceTeam.Gradience.json` and `com.github.GradienceTeam.Gradience.Devel.json` by this file : https://github.com/flathub/com.github.GradienceTeam.Gradience/blob/master/com.github.GradienceTeam.Gradience.json ?
> 
> At this point, I'm just so confused I'm asking you to try the more conventional method to build libsass. But, what's happening is that GCC is failing with error code 137. Unfortunately, libtool doesn't print the error, just the error code (why the fuck, btw), and, gcc does not document its error codes, sooooo, we're kinda working in the dark here.

Yea, I googled this error for hours yesterday, but I couldn't find any documentation about it, nor did anyone has posted about this anywhere, looks like.

**Comment by LyesSaadi** [comment] 2022-08-30 03:04
> Yea, I googled this error for hours yesterday, but I couldn't find any documentation about it, nor did anyone has posted about this anywhere, looks like.

I just tried to grep gcc's source code, and you'd be surprised to learn how much 137 is mentioned there :P !

**Comment by tfuxu** [comment] 2022-08-30 03:09
> > Yea, I googled this error for hours yesterday, but I couldn't find any documentation about it, nor did anyone has posted about this anywhere, looks like.
> 
> I just tried to grep gcc's source code, and you'd be surprised to learn how much "137" is mentioned there (it's overflowing the terminal's buffer) :P !

No wonder, GCC source code is massive!

**Comment by DivineBicycle** [comment] 2022-08-30 03:55
> > I tried again without OOMD enabled, and I got the same error. However I did not run out of memory. How odd. I'll upload the build log again. [Here](https://gist.github.com/DivineBicycle/e076a5ef75028a0a18c6a127bd5b29b9)
> 
> That's really weird. I was able to compile every dependency on a 4GB ram vm, so maybe as Lyes says, there's no OOM business here. Maybe it is the version of Builder you're using (I'm on version 43.alpha1), that have that kinds of bugs. Here's my full build log [here](https://gist.github.com/tfuxu/d0b7838b47d9098e1743d9cd6d4c41fd) if you want to compare it with yours.

I just tried again with the nightly version of Gnome Builder from Flatpak. [Here's](https://gist.github.com/DivineBicycle/e076a5ef75028a0a18c6a127bd5b29b9) the build log, although I expect it will be the same.

**Comment by DivineBicycle** [comment] 2022-08-30 03:56
> No wonder, GCC source code is massive!

LLVM for life! :)

**Comment by LyesSaadi** [comment] 2022-08-30 04:00
Ok, so, it's not the same. It's failing at the python3-lxml build here, not in libsass.

It might either be OOM then, or some sort of specific set limit that makes the build stop and output a 137, looking at how consistent it is with libsass.

**Comment by DivineBicycle** [comment] 2022-08-30 04:13
> Ok, so, it's not the same. It's failing at the python3-lxml build here, not in libsass.
> 
> It might either be OOM then, or some sort of specific set limit that makes the build stop and output a 137, looking at how consistent it is with libsass.

Interesting, is that possibly a Gnome Builder error code then?

**Comment by LyesSaadi** [comment] 2022-08-30 04:18
Nope, the error code is clearly gcc's. And it's clearly the OOM error code. But, I'm not certain that it is actually killed by the OOM killer itself? Or it's an OOM killer that targets all processes that reach a certain memory limit for each processes...? That is very weird.

Could you tell us how much RAM do you have and what OOM killer your Arch Linux installation uses if any?

**Comment by DivineBicycle** [comment] 2022-08-30 04:23
> Could you tell us how much RAM do you have
16 Gigabytes with an 8 Gigabyte zram device.

> what OOM killer your Arch Linux installation uses if any

Well that's funny, when that was first suggested it I disabled it (systemd-oomd). However it seems to have come back online. I will try to stop it and try the build again

**Comment by DivineBicycle** [comment] 2022-08-30 04:47
No luck, still didn't work. [Here's](https://gist.github.com/DivineBicycle/e076a5ef75028a0a18c6a127bd5b29b9) the build log.

**Comment by tfuxu** [comment] 2022-08-30 11:11
> Well that's funny, when that was first suggested it I disabled it (systemd-oomd). However it seems to have come back online. I will try to stop it and try the build again
> 

If you want to disable oomd pernamently you would need to mask it: https://askubuntu.com/a/1405588

**Comment by tfuxu** [comment] 2022-08-30 11:15
@DivineBicycle 
Also, have you tried to just compile Gradience (to flatpak, not in meson) from terminal? If yes, does it compiled successfully?

**Comment by tfuxu** [comment] 2022-08-30 11:16
> @DivineBicycle 
> Also, have you tried to just compile Gradience (to flatpak, not using meson) from terminal? If yes, does it compiled successfully?

**Comment by DivineBicycle** [comment] 2022-08-30 12:05
> 
> > Well that's funny, when that was first suggested it I disabled it (systemd-oomd). However it seems to have come back online. I will try to stop it and try the build again
> > 
> 
> If you want to disable oomd pernamently you would need to mask it: https://askubuntu.com/a/1405588

I realised it was because the socket was still active, I disabled both and that fixed it but I masked it anyway.

**Comment by DivineBicycle** [comment] 2022-08-30 12:14
flatpak-buidler has stopped working, tried piping the output of the command to a file but it didn't pipe properly

**Comment by DivineBicycle** [comment] 2022-08-30 13:36
![image](https://user-images.githubusercontent.com/78889625/187451244-891c17b9-b68d-4df7-92c9-defde46a0c01.png)
Actually it looks as if I had it enabled contrary to the default. I'll try resetting all Gradience's settings to default through Flatseal and try again

**Comment by DivineBicycle** [comment] 2022-08-30 13:40
I just tried that and still no luck.

**Comment by tfuxu** [comment] 2022-08-30 13:46
> I just tried that and still no luck.

Try resetting permissions by typing: `flatpak permission-reset com.github.GradienceTeam.Gradience` as said in [this](https://github.com/flatpak/flatpak-builder/issues/389#issuecomment-903472821) comment.

**Comment by LyesSaadi** [comment] 2022-08-30 13:47
And `flatpak permission-reset com.github.GradienceTeam.Gradience.Devel` as well.

**Comment by DivineBicycle** [comment] 2022-08-30 23:43
That worked! I can now try to actually fix bugs :)

**Closed** 2022-08-30 23:43 UTC
Labels: bug, build

**Comment by tfuxu** [comment] 2022-08-30 23:54
> That worked! I can now try to actually fix bugs :)

Nice!
