### ISSUE TITLE
feat: Qt Themes for Gnome

### ISSUE THREAD

**Issue by Heus-Sueh** [GradienceTeam/Gradience#761] opened 2023-05-02 18:18 UTC
### Feature description

what i am proposing is to be able to change the QT theme to something more like LibAdwaita

maybe a toggle to download this theme like firefox toggle in Advanced tab -> Plugins: [KvLibadwaita](https://github.com/GabePoel/KvLibadwaita)
![image](https://user-images.githubusercontent.com/98482469/235750227-323a9f2d-1300-4008-8f57-eff30f3bc8c8.png)

### Additional Context

I don't think I have any information that will help.

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix-UFO** [comment] 2023-05-02 19:06
Thanks for taking time to propose this feature, we appreciate this! Unfortunately, this feature request is duplicate of https://github.com/GradienceTeam/Plugins/issues/15, https://github.com/GradienceTeam/Plugins/issues/4 and https://github.com/GradienceTeam/Gradience/issues/729

**Closed by daudix-UFO** 2023-05-02 19:06 UTC
Labels: enhancement, feature-request
