### ISSUE TITLE
Firefox GNOME theme: toolbar separator turns white when unfocused

### ISSUE THREAD

**Issue by notpeelz** [GradienceTeam/Gradience#732] opened 2023-03-08 02:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Using the Firefox GNOME theme, combined with Gradience's plugin, the "toolbar separator" turns white when unfocused.

### To Reproduce

1. Install the latest version of the Firefox GNOME theme
2. Enable the "Firefox GNOME Theme" plugin
3. Apply Gradience "Pretty purple" theme
4. (Re)start Firefox

### Screenshots

With the patched Firefox GNOME theme (focused):
<img src="https://user-images.githubusercontent.com/920910/223599384-b2d25e9b-ecf4-4ad3-b660-7eedf1c061eb.png" width="400" />

With the patched Firefox GNOME theme (unfocused):
<img src="https://user-images.githubusercontent.com/920910/223599388-dbf6d762-de6b-43df-bb1a-02f315e6fca8.png" width="400" />

With the default Firefox GNOME theme (focused):
<img src="https://user-images.githubusercontent.com/920910/223599623-e061e814-938f-415e-85d8-340870f70ad7.png" width="400" />

With the default Firefox GNOME theme (unfocused):
<img src="https://user-images.githubusercontent.com/920910/223599840-0060d2aa-ac83-4029-a63b-2915134cc2f1.png" width="400" />

### OS

Arch

### DE/WM version

GNOME 43.3

### Version

0.4.0

### Installation method

Flatpak from Flathub

### Additional context

Firefox version: 110

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by notpeelz** [comment] 2023-03-08 03:39
Same issue occurs with the sidebar:
![image](https://user-images.githubusercontent.com/920910/223613639-8d0f0d5c-f7f0-4f45-b46f-34afcd59dd0c.png)

**Comment by notpeelz** [comment] 2023-03-08 04:21
Whoops, didn't realize this was already reported in #640

**Comment by daudix-UFO** [comment] 2023-04-19 02:05
Duplicate of #640

**Closed by daudix-UFO** 2023-04-19 02:05 UTC
Labels: type/bug, area/firefox-gnome-theme
