### ISSUE TITLE
Preset Saving Incorrectly

### ISSUE THREAD

**Issue by BigCityCat** [GradienceTeam/Gradience#656] opened 2022-11-18 21:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If I created a preset and save it as green. Then create a new preset and save it as blue. When I go back to select the green theme and apply it. It will only apply as blue. The preset for green is showing in user presets but it does not apply as green. It will only apply as the last saved theme. I am unable to have multiple user presets to choose from and have to recreate anytime I would like to change presets.

### To Reproduce

create preset and save it. Create new preset and save it. Unable to apply previous preset.

### Expected behavior

I would expect to be able to have multiple presets saved and apply when necessary.n/a

### Screenshots

N/A

### OS

Ubuntu 22.10

### Version

0.3.1

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daudix-UFO** [comment] 2022-11-19 16:56
This issue is fixed and will be shipped with 0.3.2

Closing as this is duplicate of #624

**Closed by daudix-UFO** 2022-11-19 16:56 UTC
