### ISSUE TITLE
bug: Broken UI after restarted

### ISSUE THREAD

**Issue by Xyphyn** [GradienceTeam/Gradience#678] opened 2022-12-20 00:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

For some reason, if I try using Gradience twice, this is what appears on the second launch:
![image](https://user-images.githubusercontent.com/80978739/208552625-7122cfa4-5839-4e1f-8874-d01fc32d3b86.png)
I cannot preview my changes and it looks disgusting.

### To Reproduce

1. Install Gradience
2. do some stuff and enjoy libadwaita while you can
3. Restart the app
4. Be disgusted by the broken UI

### Expected behavior

Gradience should have used libadwaita and showed my theme changes as i was editing them.

### Screenshots

![image](https://user-images.githubusercontent.com/80978739/208552685-466a66aa-544d-41a7-ac0e-84f8ccf2a82a.png)

### OS

Fedora Linux 37 (Workstation Edition)

### Version

0.3.3

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tfuxu** [comment] 2022-12-20 11:12
Duplicate of issue #563. A solution for this bug should be in 2 last comments of this issue.

**Closed** 2022-12-20 11:12 UTC
Labels: type/bug, type/duplicate, build/flatpak

**Comment by Xyphyn** [comment] 2022-12-20 19:12
That doesn't fix it.
