### ISSUE TITLE
bug: disk reads/writes while window is resized

### ISSUE THREAD

**Issue by EntityinArray** [GradienceTeam/Gradience#339] opened 2022-09-04 15:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I agree to follow this project's Code of Conduct
### What happened?

I have a spare old HDD in my PC that runs Linux, disk is old and makes audible cracking noise every read/write operation.
Every time I resize Gradience window, HDD makes a cracking noise and resizing is much slower than in other apps.
This leads me to believe that Gradience does unnecessary blocking reads/writes to filesystem every frame while window is being resized.

Problem only occurs when resizing the main window only, resizing any other window of the app (Preferences window, Presets window) doesn't cause this problem

### To Reproduce

1. In the app, try resizing the main window
2. Unresponsive behavior and disk activity every frame while window is being resized.

### Expected behavior

Smooth resizing without stutters and disk activity

### OS

Nobara Linux 36 (based on Fedora)

### Version

0.2.2

### Installation method

Flatpak from Flathub

### Additional context

Thank you for developing amazing software! If you need any extra info, I will be glad to help!

**Comment by 0xMRTT** [comment] 2022-09-04 16:00
Will try to reproduce but currently I don't see why 😅

**Comment by 0xMRTT** [comment] 2022-09-12 20:00
Strange because Gradience only do write when you apply, save, open the preset manager and use the preset manager

**Comment by EntityinArray** [comment] 2022-09-13 19:05
@0xMRTT Hi, thank you for looking into this, does Gradience window slightly stutter during resizing for you as well?
I recently moved my system to SSD, so stutter is gone for me. However, I installed iotop (program that shows disk usage) and while resizing Gradience main window, it shows that Gradience writes to disk at a rate of ~5 MB/s
I recorded a video that demonstrates the bug:
[disk_write_on_resize.webm](https://user-images.githubusercontent.com/18554021/189988402-2ae63f73-a678-44ad-a2ba-041d8366257f.webm)

**Comment by 0xMRTT** [comment] 2022-09-13 19:23
Strange, thanks for the video. Will try to fix because it's abnormal.

**Comment by 0xMRTT** [comment] 2022-09-15 20:18
Impossible to reproduce the issue :/

**Comment by EntityinArray** [comment] 2022-09-16 04:55
Hi, did you look into iotop? It doesn't do any writes on your end?

**Comment by 0xMRTT** [comment] 2022-09-16 05:07
Yes but it do for @daudix-UFO

**Comment by EntityinArray** [comment] 2022-09-16 07:25
I see, thank you. I'm new to issue reporting, maybe I should report this to Gnome, maybe they can figure this out? I have a feeling that this is a libadwaita bug

**Comment by 0xMRTT** [comment] 2022-09-16 07:58
Is it the same with others gtk4 + libadwaita apps ?

**Comment by EntityinArray** [comment] 2022-09-16 08:25
No, other libadwaita apps don't have this problem, but your app has a lot of adaptive stuff, like tabs that move to the bottom and then disappear as window shrinks, etc. I'm not sure though, I will try to debug it further when I get back from work. I will try to install software that shows disk activity on a file basis, to see which files are getting written on resize.

**Comment by daudix-UFO** [comment] 2022-09-16 09:10
@0xMRTT Are you sure that the window state writes only when app is closing and not on resize?

**Comment by 0xMRTT** [comment] 2022-09-16 09:51
I need to check because I followed the official documentation

**Comment by EntityinArray** [comment] 2022-09-17 04:08
Every frame while resizing the main window, this file is getting accessed:
```
/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0/settings
```

I looked at the process activity through strace via this command: ```sudo strace -f -p gradience_pid -e access```
While resizing, it was constantly opening and writing this file:
```
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0/settings", R_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0/settings", W_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0/settings", X_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0", W_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0/settings", R_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0/settings", W_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0/settings", X_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0", W_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0/settings", R_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0/settings", W_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0/settings", X_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0", W_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0/settings", R_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0/settings", W_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0/settings", X_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0", W_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0/settings", R_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0/settings", W_OK) = 0
[pid 11786] access("/home/entityinarray/.var/app/com.github.GradienceTeam.Gradience/config/glib-2.0/settings", X_OK) = 0

```
I think this is the behaviour that causes write activity we were seeing in iotop

**Comment by EntityinArray** [comment] 2022-09-17 04:49
Reported an issue to GLib gitlab: https://gitlab.gnome.org/GNOME/glib/-/issues/2752

**Comment by tfuxu** [comment] 2022-09-17 14:34
> Reported an issue to GLib gitlab: https://gitlab.gnome.org/GNOME/glib/-/issues/2752

I don't think that was necessary IMO. This isn't a bug in GLib, but a appropriate behavior, as `default-width` and `default-height` are changed constantly, and therefore it will obviously make a read/write spam if a function that is meant to be executed every time a said property is changed, gets a signal that this property was changed tens or hundreds of times.

**Comment by tfuxu** [comment] 2022-09-17 17:15
Okay, I think we can finally close this issue, as #446 has been merged.

**Closed by tfuxu** 2022-09-17 17:15 UTC
Labels: bug

**Comment by 0xMRTT** [comment] 2022-09-17 17:21
Yes, 👍🚀

Thanks you @tfuxu
