### ISSUE TITLE
feat: Apply Libadwita-style theme to QT apps

### ISSUE THREAD

**Issue by IntoTheVoid-900** [GradienceTeam/Gradience#729] opened 2023-02-28 00:19 UTC
### Feature description

It would help unify the look of a user's desktop if you allowed theming QT apps as well. In an effort to do this, I installed [KvLibadwaita](https://github.com/GabePoel/KvLibadwaita), but as expected it didn't adopt the Gradience colour scheme. Can you make it generate a Kvantum theme based on KvLibadwaita but with your colour scheme, similar to the Firefox GNOME style plugin?

### Did you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/GradienceTeam/Gradience/blob/main/CODE_OF_CONDUCT.md).

**Comment by daudix-UFO** [comment] 2023-04-19 02:10
Duplicate of https://github.com/GradienceTeam/Plugins/issues/15 and https://github.com/GradienceTeam/Plugins/issues/4

**Closed by daudix-UFO** 2023-04-19 02:10 UTC
Labels: enhancement, feature-request, area/plugin
