### ISSUE TITLE
bug: Nothing works under Arch Linux

### ISSUE THREAD

**Issue by aspizu** [GradienceTeam/Gradience#824] opened 2023-09-19 13:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

nothing works

### To Reproduce

fix it

### OS

Arch Linux

### DE/WM version

Hyprland

### Version

gradience --version is not a command

### Installation method

AUR

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianschelb** [comment] 2023-09-21 11:26
For sure you do not actually think that anyone can help you based on this problem description

**Comment by 0xMRTT** [comment] 2023-09-21 17:17
maybe more details about the issue can be helpful indeed

**Comment by ThatOneCalculator** [comment] 2023-09-27 21:01
I ran into some problems on Arch with it not launching -- `yay -S python-material-color-utilities --overwrite "*"` fixed it for me.

**Comment by hrdkmishra** [comment] 2023-10-10 16:32
i installed gradience-git via aur and it doesn open at all

**Comment by hrdkmishra** [comment] 2023-10-10 16:33
> I ran into some problems on Arch with it not launching -- `yay -S python-material-color-utilities --overwrite "*"` fixed it for me.

this wasnt helpful for me

**Comment by hrdkmishra** [comment] 2023-10-10 16:43
mb everything is fixed after reboot and `yay -S python-material-color-utilities --overwrite "*"` this was helpful

**Comment by hrdkmishra** [comment] 2023-10-11 05:32
again it aint working no more after adding presets

**Comment by 0xMRTT** [comment] 2023-10-11 10:28
> again it aint working no more after adding presets

what's not working ?

**Comment by hrdkmishra** [comment] 2023-10-12 09:15
> what's not working ?

as when i try open the application it just never launches on gnome 45 and even if try to open via terminal i.e _gradience not the cli_ one it just dont show any error it never runs.

i can confirm **flatpak works completely fine** but the arch package aint working

**Comment by 0xMRTT** [comment] 2023-10-12 20:03
Maybe a packaging issue i'll check

**Comment by ThatOneCalculator** [comment] 2023-10-12 20:14
I can't reproduce this issue.

**Comment by UnknownCoder56** [comment] 2023-12-24 16:20
`yay -S python-material-color-utilities --overwrite "*"` fixes it for me, before this the UI was glitching out horribly.

**Comment by UnknownCoder56** [comment] 2023-12-24 16:28
nvm its back after applying a theme

**Comment by daudix** [comment] 2024-01-03 18:21
Closing for now, if someone will have this kind of issue again we can reopen it

**Closed by daudix** 2024-01-03 18:21 UTC
Labels: type/bug
