### ISSUE TITLE
Gnome 43 - Quick Settings not styled

### ISSUE THREAD

**Issue by mystrdat** [GradienceTeam/Gradience#657] opened 2022-11-19 01:30 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

I can't seem to get Gnome 43 Quick Settings menu styled according to the selected color preset, are there any extra steps necessary for the popup to follow the Gradience theme? Using Flatpak

### To Reproduce

1. Apply a theme in Gradience
2. Reboot / Logout + Login
3. Check Quick Settings, it's not changed

### Expected behavior

Quick Settings menu should follow the theme

### OS

Fedora Silverblue 37

### Version

0.3.1

### Installation method

Flatpak from Flathub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xMRTT** [comment] 2022-11-19 05:53
Hi,

Quick settings are part of the gnome shell, so they will come with the gnome shell plugin

**Comment by daudix-UFO** [comment] 2022-11-19 16:53
As this is duplicate of #618 I am closing

**Closed by daudix-UFO** 2022-11-19 16:53 UTC
