### ISSUE TITLE
bug: Flatpaked Gradience writes to internal config directory

### ISSUE THREAD

**Issue by zehkira** [GradienceTeam/Gradience#710] opened 2023-01-29 15:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When Gradience is installed via Flatpak and used to theme Libadwaita apps, it adds a global override to allow all apps to read `~/.config/gtk-4.0`, but writes the CSS to `~/var/app/com.github.GradienceTeam.Gradience/config/gtk-4.0/`.

Because of this, no themes are applied to Libadwaita apps.

### Screenshots

![internal config dir content](https://user-images.githubusercontent.com/111002801/215338294-4a58329a-b48c-40c8-8760-db609d235773.png)

### OS

Pop!_OS 22.04 LTS

### Version

0.3.3

### Installation method

Flatpak from Flathub

### Additional context

As a workaround, I copied the files to the correct directory manually.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LyesSaadi** [comment] 2023-01-29 16:14
Huh... Weird... I can't reproduce on my side. It doesn't write anything to `~/.var/app/com.github.GradienceTeam.Gradience/config/gtk-4.0/` as well in my case.

Can you maybe try to reboot the session ? Maybe is there something wonky with flatpak ?

**Comment by tfuxu** [comment] 2023-01-29 17:01
I also can't reproduce this bug.
![Screenshot from 2023-01-29 17-58-47](https://user-images.githubusercontent.com/73042332/215342880-67aa9dbe-83a3-46da-acf5-f0ff98c21eb6.png)

**Comment by zehkira** [comment] 2023-01-29 17:16
> You should check if a `xdg-config/gtk-4.0` path is allowed in your global Flatpak permissions.

![image](https://user-images.githubusercontent.com/111002801/215343453-9dea3944-0b3a-4b03-b6cd-882e075ca91e.png)


I can also no longer reproduce this. Maybe this is something that can only happen in some weird edge case during the initial setup.

**Comment by tfuxu** [comment] 2023-01-29 17:32
> I can also no longer reproduce this. Maybe this is something that can only happen in some weird edge case during the initial setup.

Hmm, interesting. Since this is no longer reproducible by any of us, I'm closing this issue, but if you find something interesting about it, please send you findings here. I'll also look into this when I'll be [reworking preset internals](https://github.com/GradienceTeam/Gradience/issues/706).

**Closed by tfuxu** 2023-01-29 17:32 UTC
Labels: type/bug, build/flatpak
