### ISSUE TITLE
bug: gradience fails to start

### ISSUE THREAD

**Issue by wat9rz** [GradienceTeam/Gradience#434] opened 2022-09-16 00:40 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What happened?

full error log `$ ~ gradience 
Traceback (most recent call last):
  File "/usr/bin/gradience", line 64, in <module>
    from gradience import main
  File "/usr/lib/python3.10/site-packages/gradience/main.py", line 29, in <module>
    from .window import GradienceMainWindow
  File "/usr/lib/python3.10/site-packages/gradience/window.py", line 32, in <module>
    from .app_type_dialog import GradienceAppTypeDialog
  File "/usr/lib/python3.10/site-packages/gradience/app_type_dialog.py", line 25, in <module>
    class GradienceAppTypeDialog(Adw.MessageDialog):
  File "/usr/lib64/python3.10/site-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Adw' object has no attribute 'MessageDialog'
$ ~ `

### To Reproduce

start gradience from terminal. will not open from the dekstop

### Expected behavior

i expected for gradience to start normally

### OS

Fedora 36 Workstation

### Version

1.2.0

### Installation method

Other

### Additional context

i installed gradience from dnf copr

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AdwCustomizer** [comment] 2022-09-16 00:41
Welcome on Gradience. 🥳 We really appreciate your contribution. The core team will review your issue as soon as possible. You can also join the matrix room https://matrix.to/#/#Gradience:matrix.org or the discord server https://discord.com/invite/rwNDGPJf

**Comment by 0xMRTT** [comment] 2022-09-16 05:08
Hi,

It's a problem with libadwaita you must have libadwaita> 1.2.beta

Also, try to update your app to the latest version

**Comment by tfuxu** [comment] 2022-09-16 10:40
This is a duplicate of an issue https://github.com/GradienceTeam/Gradience/issues/344.

You just need to type:
```
sudo dnf upgrade
```
as stated in this comment: https://github.com/GradienceTeam/Gradience/issues/344#issuecomment-1237258641

**Closed by tfuxu** 2022-09-16 10:40 UTC
Labels: bug, triage
