### ISSUE TITLE
feat: Light/Dark Presets

### ISSUE THREAD

**Issue by Radical4ever** [GradienceTeam/Gradience#12] opened 2022-07-22 15:10 UTC
It would be great if there is an option for applying the settings on both light/dark theme, bc when i edit the theme it just applies it for one theme and makes dark mode not working

**Comment by ArtyIF** [comment] 2022-07-22 15:13
Is it possible to do that though with gtk.css? Let me check.

**Comment by ArtyIF** [comment] 2022-07-22 15:15
Since my other email didn't get sent here for some reason - yes, it's possible. Noted.

**Comment by Radical4ever** [comment] 2022-07-22 15:19
i leave you my `gtk.css` file that i use for that:
@define-color accent_color @green_4;
@define-color accent_bg_color @green_4;
@define-color window_bg_color;
@define-color window_fg_color;
@define-color headerbar_bg_color;
@define-color headerbar_fg_color;
@define-color popover_bg_color;
@define-color popover_fg_color;
@define-color view_bg_color;
@define-color view_fg_color;
@define-color card_bg_color rgba(255, 255, 255, 0.08);
@define-color 

and it works both with adw-gtk3 theme just paste the same file over `gtk-3.0`

**Comment by Radical4ever** [comment] 2022-07-22 15:33
Yup, that works for now!

**Comment by ArtyIF** [comment] 2022-07-22 16:08
Wait, why would it do that for you? It doesn't for me. It always applies the same theme regardless of the color scheme chosen.

**Comment by ArtyIF** [comment] 2022-07-22 16:11
Are you copying those CSS files into your theme or something? Because this program doesn't change the theme files, it just copies the parameters to `~/.config/gtk-4.0/gtk.css` (or 3.0 for gtk3).

**Comment by Radical4ever** [comment] 2022-07-22 17:29
> Are you copying those CSS files into your theme or something? Because this program doesn't change the theme files, it just copies the parameters to `~/.config/gtk-4.0/gtk.css` (or 3.0 for gtk3). That file is always applied about the selected theme or app's theme (unless the app sets the priority higher like I do, which is technically not recommended) no matter the chosen color scheme.

i dont use a theme or something else, i just add the parameters for the accent color and the rest i leave it empy (so it uses the default value) and then i just save it in ~/.config/gtk-4.0 or gtk-3.0, so it always use the same color on all apps.

**Comment by Radical4ever** [comment] 2022-07-22 17:30
just save it as gtk.css and put it in gtk-4.0 and that should work on libadwaita apps and for adw-gtk3 i do the same and restart the gtk3 apps

**Comment by ArtyIF** [comment] 2022-07-22 17:31
And it doesn't apply when you have it set to dark, right?

**Comment by ArtyIF** [comment] 2022-07-22 17:33
> just save it as gtk.css and put it in gtk-4.0 and that should work on libadwaita apps and for adw-gtk3 i do the same and restart the gtk3 apps

It's supposed to automatically get put in gtk-4.0 and gtk-3.0.

**Comment by Radical4ever** [comment] 2022-07-22 17:36
> > just save it as gtk.css and put it in gtk-4.0 and that should work on libadwaita apps and for adw-gtk3 i do the same and restart the gtk3 apps
> 
> It's supposed to automatically get put in gtk-4.0 and gtk-3.0.

oh, sorry! i was talking about the gtk.css file i mentioned earlyer that i made

> i leave you my `gtk.css` file that i use for that: @define-color accent_color @green_4; @define-color accent_bg_color @green_4; @define-color window_bg_color; @define-color window_fg_color; @define-color headerbar_bg_color; @define-color headerbar_fg_color; @define-color popover_bg_color; @define-color popover_fg_color; @define-color view_bg_color; @define-color view_fg_color; @define-color card_bg_color rgba(255, 255, 255, 0.08); @define-color

it just with this one that i made that i dont have the issue but when the app makes its own makes one with only the light theme set.

**Comment by ArtyIF** [comment] 2022-07-22 17:41
Ohhhhh. You can change the accent color like that in the app. Press the 
pencil icon next to the needed values (Accent Standalone Color and 
Accent Background Color in this case) and enter @green_4. If you want 
to use a dark theme, use the dropdown in the top to select the dark 
preset (do it before the @green_4 thing).

**Comment by Radical4ever** [comment] 2022-07-22 18:11
yeah i know that, but what i mean is that if its possible to made an option to apply both light/dark theme like that.

**Comment by ArtyIF** [comment] 2022-07-22 18:15
> yeah i know that, but what i mean is that if its possible to made an option to apply both light/dark theme like that.

Like, apply separate color schemes for light and dark themes? Not yet.

**Comment by Radical4ever** [comment] 2022-07-22 21:09
> > yeah i know that, but what i mean is that if its possible to made an option to apply both light/dark theme like that.
> 
> Like, apply separate color schemes for light and dark themes? Not yet.

not separate, i mean like, an only color for both light/dark theme, without going to edit the 2 themes separately and with that you could switch between theme.

**Comment by Radical4ever** [comment] 2022-07-22 21:10
maybe i have to make a video to better explain myself 😅🤣

**Comment by Radical4ever** [comment] 2022-07-22 21:14
this is what i'm trying to mean (i couldnt make a video it stops when i change it)
![Captura desde 2022-07-22 18-13-13](https://user-images.githubusercontent.com/83252104/180569419-b1124bdc-55a3-49c9-9ac6-25fe5d71d654.png)

**Comment by ArtyIF** [comment] 2022-07-22 23:59
Same theme for light and dark? It already does that.00:09, July 23, 2022, Radical4ever ***@***.***>:


yeah i know that, but what i mean is that if its possible to made an option to apply both light/dark theme like that.

Like, apply separate color schemes for light and dark themes? Not yet.

not separate, i mean like, an only color for both light/dark theme, without going to edit the 2 themes separately and with that you could switch between theme.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
-- Sent from Yandex Mail for mobile

**Comment by Radical4ever** [comment] 2022-07-23 02:16
> Same theme for light and dark? It already does that

i mean like an option to apply the colors without doing the same thing on the dark variant

**Comment by ArtyIF** [comment] 2022-07-23 09:57
Okay I think I understood what you mean. Have one preset for both light and dark theme so you didn't have to apply a different color scheme when you change the theme. Is that right?

**Comment by ArtyIF** [comment] 2022-07-23 09:58
As in, one preset has a variant for light and dark theme, and when applying the scheme, you're still able to switch between light and dark without reapplying the scheme.

**Comment by Radical4ever** [comment] 2022-07-23 12:49
> Okay I think I understood what you mean. Have one preset for both light and dark theme so you didn't have to apply a different color scheme when you change the theme. Is that right?

Yes, is that

**Comment by Radical4ever** [comment] 2022-07-23 12:49
> As in, one preset has a variant for light and dark theme, and when applying the scheme, you're still able to switch between light and dark without reapplying the scheme.

Yeah, something like that

**Comment by lassekongo83** [comment] 2022-07-27 05:41
I've not tested this, but here's how it could be done.

1. Create 2 files containing the light and dark themes. For example: `gtk-light.css` and `gtk-dark.css`.
2. Detect if `gsettings set org.gnome.desktop.interface color-scheme` is set to `'default'` or `'dark'`.
3. If set to dark then symlink `gtk-dark.css` to `gtk.css` or vice versa.

**Comment by ArtyIF** [comment] 2022-07-27 05:47
I believe Libadwaita has a built-in function for detecting the color scheme. Also it won't change the theme automatically when you toggle it in system settings, so it's not that much different from how it works now.

**Comment by daudix-UFO** [comment] 2022-07-28 14:42
> I believe Libadwaita has a built-in function for detecting the color scheme. Also it won't change the theme automatically when you toggle it in system settings, so it's not that much different from how it works now.

I have done GTK3 auto-switch using [Night Theme Switcher](https://nightthemeswitcher.romainvigier.fr/) extension

**Comment by ArtyIF** [comment] 2022-07-28 14:44
No, I mean that if in system settings you switch to Light theme when 
you have a dark color scheme applied, currently the color scheme won't 
change to light.

**Comment by ArtyIF** [comment] 2022-07-28 15:11
I mean something like this, in case you don't mean that already (all Libadwaita apps):

![ezgif com-gif-maker](https://user-images.githubusercontent.com/8017858/181573392-2f0ddc0a-362f-4d00-bc96-80698808f2eb.gif)

**Comment by daudix-UFO** [comment] 2022-07-28 15:28
That happens when you apply custom CSS with AdwCustomizer

**Comment by daudix-UFO** [comment] 2022-07-28 15:30
And when you reset CSS, everything works again

**Comment by 0xMRTT** [comment] 2022-08-11 16:37
![image](https://user-images.githubusercontent.com/105598867/184185695-2368f6ad-069b-4877-836b-b3840e4336e5.png)

**Comment by cachandlerdev** [comment] 2022-09-03 18:11
I see that this issue was marked as completed. In that case, how do I make use of light and dark modes using the preset themes? It seems like I have an option to select and apply one of the two, but this seems to break the "Light" and "Dark" functionality in Gnome Settings.

**Comment by 0xMRTT** [comment] 2022-09-03 18:38
Hi @cachandlerdev 

For some reason, Adwaita and Gtk are ignoring `gtk-dark.css`, so i've disabled this functionnality. This will come back very soon :rocket:

**Comment by lutzseverino** [comment] 2022-09-14 18:35
Huh, I just found out myself “reset”ing fixes the dark/light schemes, I feel it's rather unintuitive though. Should we consider changing the naming on “reset” and “restore”? Their differences are not exactly clear.

Maybe explain inside the dialog? Since it's a destructive action, more attention should be drawn to the user.

**Comment by daudix-UFO** [comment] 2022-09-14 18:55
I agree 👍

**Comment by 0xMRTT** [comment] 2022-09-14 18:58
@daudix-UFO, do you have any proposal about the name ?

**Comment by daudix-UFO** [comment] 2022-09-14 19:08
Not sure, maybe something like warning dialog with `continue | cancel` options?

**Comment by 0xMRTT** [comment] 2022-09-14 19:12
Okay 👌

**Comment by daudix-UFO** [comment] 2022-09-14 19:13
👌

**Comment by daudix-UFO** [comment] 2022-10-06 17:27
> I've not tested this, but here's how it could be done.
> 
>     1. Create 2 files containing the light and dark themes. For example: `gtk-light.css` and `gtk-dark.css`.
> 
>     2. Detect if `gsettings set org.gnome.desktop.interface color-scheme` is set to `'default'` or `'dark'`.
> 
>     3. If set to dark then symlink `gtk-dark.css` to `gtk.css`, and if default symlink the other file.

What about trying to do this?

**Comment by daudix-UFO** [comment] 2022-10-06 17:27
Or something like this:
https://github.com/lassekongo83/adw-gtk3/blob/main/gtk4.md

**Comment by 0xMRTT** [comment] 2022-10-06 17:59
The theme idea is the best one because with this idea, we will be able to customise GNOME shell

**Comment by daudix-UFO** [comment] 2022-10-06 18:55
Good, one more task for 0.4.0

**Comment by ArtyIF** [comment] 2022-10-11 08:02
Yes it is. Noted.

**Comment by 0xMRTT** [comment] 2022-10-11 08:03
I'm working on this because it's related to #618

**Comment by lutzseverino** [comment] 2023-01-25 10:42
How is this going along? This problem should be a priority, since some people switch themes quite often. Night Theme Switcher is rendered useless with Gradience if this persists.

**Comment by ArtyIF** [comment] 2023-01-25 12:45
I think this can be worked around by generating two files for light and dark and creating a GApplication that'll switch the `gtk.css` file periodically. At least, until the recoloring API becomes a thing in the stable version

**Comment by daudix-UFO** [comment] 2023-01-25 15:42
The problem is that you still need to restart the app, and apps like nautilus will need to be killed every time

**Comment by tfuxu** [comment] 2023-01-31 00:10
With current `libadwaita` implementation of custom themes (or more accurately, a lack of it), it is impossible to add support for seamless transitions between light/dark presets. As noted by daudix, every currently running GTK application on user's system would need to be restarted, or ideally the whole DE session would need to be restarted, making the whole feature very clunky to use.

I'm closing and locking this issue for now, as until [AdwColorTheme](https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/369) and its recoloring API becomes available, the discussion here will lead to nothing.
<sub> If you found some method that could be used / GNOME Team has added some sort of support for this and we didn't noticed yet, it would be really appreciated if you inform us of your findings on [Matrix](https://matrix.to/#/#Gradience:matrix.org) or on [Discussions](https://github.com/GradienceTeam/Gradience/discussions). </sub>

**Closed by tfuxu** 2023-01-31 00:10 UTC
Labels: enhancement, help wanted, status/wontfix, area/preset
